export const ADD_ADDRESS_REQUEST = 'ADD_ADDRESS_REQUEST';
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
export const ADD_ADDRESS_FAILURE = 'ADD_ADDRESS_FAILURE';


export const DELETE_ADDRESS_BY_ID_REQUEST = 'DELETE_ADDRESS_BY_ID_REQUEST';
export const DELETE_ADDRESS_BY_ID_SUCCESS = 'DELETE_ADDRESS_BY_ID_SUCCESS';
export const DELETE_ADDRESS_BY_ID_FAILURE = 'DELETE_ADDRESS_BY_ID_FAILURE';

export const EDIT_ADDRESS_REQUEST = 'EDIT_ADDRESS_REQUEST';
export const EDIT_ADDRESS_SUCCESS = 'EDIT_ADDRESS_SUCCESS';
export const EDIT_ADDRESS_FAILURE = 'EDIT_ADDRESS_FAILURE';
